nelmio_api_doc:
    documentation:
        info:
            title: User Mangement System API
            description: This is registration endpoint
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^(?!/api) # Accepts routes under /api except /api/doc
